# 예외 Rules
disabled_rules:
  # 줄 끝 공백 or 탭
 - trailing_whitespace
 - leading_whitespace
  # FILE_END Line
 - trailing_newline
  # func 대문자 시작 ( ViewBuilder, ViewModifier 때문에 예외 처리)
 -  identifier_name
  # func 변수를 5개 이하로 제한 ( WidgetManager 수정 후 지우겠습니다 )
 - function_parameter_count

# Optional Rules
opt_in_rules:
  # 강제 언래핑 안됨
 - force_unwrapping
  
# Parameter 개수
function_parameter_count:
 warning: 5
 error: 6
 ignores_default_parameters: true

# 라인 글자수
line_length:
 warning: 170
 error: 200

# 파일 길이
file_length:
 warning: 700
 error: 1000
 ignore_comment_only_lines: false

# Tuple 정의 개수
large_tuple:
 warning: 3
 error: 4
